/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head';
// import Image from 'next/image';
import Banner from '../component/Banner';
import Footer from '../component/Footer';
// import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="bg-white dark:bg-kiwi overflow-x-hidden">
      <Head>
        <title>Country Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Footer />
    </div>
  );
}
