/* eslint-disable max-len */
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
// import Image from 'next/image';
import Banner from '../component/Banner';
import Countries from '../component/Countries';
import Footer from '../component/Footer';
import Sidebar from '../component/Sidebar';
// import styles from '../styles/Home.module.css';

export default function Home({ countries }) {
  return (
    <div className="bg-white dark:bg-kiwi overflow-x-hidden">
      <Head>
        <title>Country Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner countries={countries} />
      <div className="md:flex md:px-16 md:space-x-10 md:py-16">
        <div className="md:w-2/6">
          <Sidebar />
        </div>
        <div className="md:w-4/6 w-full">
          <Countries countries={countries} />
        </div>
      </div>
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch('https://restcountries.eu/rest/v2/all');
  const countries = await res.json();

  return {
    props: {
      countries,
    },
  };
};
Home.propTypes = {
  countries: PropTypes.shape({}),
};

Home.defaultProps = {
  countries: {},
};
